In [50]:
# buat matrix X berukuran 2x3 menggunakan numpy
import numpy as np

In [51]:
X = np.array([[77, 7], [5, 10], [4, 8]])
X

array([[77,  7],
       [ 5, 10],
       [ 4,  8]])

In [52]:
# tampilkan ukuran dari matrix X
X.shape

(3, 2)

In [53]:
X.size

6

In [54]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
X[0,:]

array([77,  7])

In [55]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
X[:,1]

array([ 7, 10,  8])

In [56]:
# ulangi soal nomor 1 menggunakan pytorch
import torch

In [57]:
X_pt = torch.tensor([[77, 7], [5, 10], [4, 8]])
X_pt

tensor([[77,  7],
        [ 5, 10],
        [ 4,  8]])

In [58]:
X_pt.shape

torch.Size([3, 2])

In [59]:
X_pt.size

<function Tensor.size>

In [60]:
X_pt[0,:]

tensor([77,  7])

In [61]:
X_pt[:,1]

tensor([ 7, 10,  8])

In [62]:
# ulangi soal nomor 1 menggunakan tensorflow
import tensorflow as tf

In [63]:
X_tf = tf.Variable([[77, 7], [5, 10], [4, 8]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[77,  7],
       [ 5, 10],
       [ 4,  8]], dtype=int32)>

In [64]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [65]:
tf.size(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [66]:
X_tf[0,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([77,  7], dtype=int32)>

In [67]:
X_tf[:,1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 7, 10,  8], dtype=int32)>