In [34]:
# buat vector x dengan ukuran 3x1
import numpy as np

x = np.array([77, 7, 5])
x

array([77,  7,  5])

In [35]:
# hitung panjang vector x
len(x)

3

In [36]:
# tampilkan ukuran vector x
x.shape

(3,)

In [37]:
# tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [38]:
# akses elemen pertama dari vector x
x[0] # zero-indexed

np.int64(77)

In [39]:
# tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.int64

In [40]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([77,  7,  5])

In [41]:
# tampilkan ukuran dari vector x_t
x_t.shape

(3,)

In [42]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[77, 7, 5]])
y

y_t = y.T
y_t

array([[77],
       [ 7],
       [ 5]])

In [43]:
# tampilkan ukuran dari vector y_t
y_t.T.shape

(1, 3)

In [44]:
# lakukan soal nomor 2 menggunakan pytorch dan tensorflow
import torch
import tensorflow as tf

In [45]:
x_pt = torch.tensor([77, 7, 5])
x_pt

tensor([77,  7,  5])

In [46]:
x_tf = tf.Variable([77, 7, 5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([77,  7,  5], dtype=int32)>