In [16]:
# buat vector x dengan ukuran 3x1
import numpy as np

x = np.array([77, 7, 5])
x

array([77,  7,  5])

In [17]:
# hitung panjang vector x
len(x)

3

In [18]:
# tampilkan ukuran vector x
x.shape

(3,)

In [19]:
# tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [20]:
# akses elemen pertama dari vector x
x[0] # zero-indexed

np.int64(77)

In [21]:
# tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.int64

In [22]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([77,  7,  5])

In [23]:
# tampilkan ukuran dari vector x_t
x_t.shape

(3,)

In [24]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[77, 7, 5]])
y

array([[77,  7,  5]])

In [25]:
# tampilkan ukuran dari vector x_t
x_t.shape

(3,)

In [26]:
# lakukan soal nomor 2 menggunakan pytorch dan tensorflow
import torch
import tensorflow as tf

In [27]:
x_pt = torch.tensor([77, 7, 5])
x_pt

tensor([77,  7,  5])

In [28]:
x_tf = tf.Variable([77, 7, 5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([77,  7,  5], dtype=int32)>